Controllers/homeController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ucprotectionplans.utility;

namespace ucprotectionplans.Controllers
{
    public class homeController : Controller
    {
        // GET: home
        public ActionResult Index(string firstname = "", string lastname = "", string phone = "", string email = "", int c = -2)
        {
            if (!Request.IsSecureConnection&&!Request.IsLocal)
            {
                string _url = "https://www.ucprotectionplans.com?v=1";
                if (!string.IsNullOrEmpty(firstname))
                {
                    _url = _url + "&firstname=" + firstname;
                }
                if (!string.IsNullOrEmpty(lastname))
                {
                    _url = _url + "&lastname=" + lastname;
                }
                if (!string.IsNullOrEmpty(phone))
                {
                    _url = _url + "&phone=" + phone;
                }
                if (!string.IsNullOrEmpty(email))
                {
                    _url = _url + "&email=" + email;
                }
                if (c != -2)
                {
                    _url = _url + "&c=" + c;
                }
                return Redirect(_url);
            }
            string useragent = Request.UserAgent.ToString();
            string biltylink = "https://www.ucesprotectionplan.com/default.aspx?rid=MEsteche";
            ViewBag.click = biltylink;
            Session["firstname"] = firstname;
            Session["lastname"] = lastname;
            Session["phone"] = phone;
            Session["email"] = email;
            Session["c"] = c; 
            return View();
        }

        public string Index2(string firstname = "", string lastname = "", string phone = "", string email = "", int c = -2)
        { 
            string useragent = Request.UserAgent.ToString();
            string biltylink = "https://www.ucesprotectionplan.com/default.aspx?rid=MEsteche";
            ViewBag.click = biltylink;
            Session["firstname"] = firstname;
            Session["lastname"] = lastname;
            Session["phone"] = phone;
            Session["email"] = email;
            Session["c"] = c;
            return insertpaymentlog2(firstname, lastname, email, phone, c);
           
        }


        public void SendnotifyAsync()
        {
            string firstname = Session["firstname"] == null ? "" : Session["firstname"].ToString();
            string lastname = Session["lastname"] == null ? "" : Session["lastname"].ToString();
            string phone = Session["phone"] == null ? "" : Session["phone"].ToString();
            string email = Session["email"] == null ? "" : Session["email"].ToString();
            string c = Session["c"] == null ? "" : Session["c"].ToString();
            string alerturl = "https://getultimateoffer.com/user/getalertmessage?fname=" + firstname + "&lname=" + lastname + "&phone=" + phone + "&email=" + email + "&c=" + c;
            if (!string.IsNullOrEmpty(firstname))
            {
                Get(alerturl);
            }
        }

        public void SendvisitAsync()
        {
            string firstname = Session["firstname"] == null ? "" : Session["firstname"].ToString();
            string lastname = Session["lastname"] == null ? "" : Session["lastname"].ToString();
            string phone = Session["phone"] == null ? "" : Session["phone"].ToString();
            string email = Session["email"] == null ? "" : Session["email"].ToString();
            string c = Session["c"] == null ? "" : Session["c"].ToString();
            int c1 = !string.IsNullOrEmpty(c) ? Convert.ToInt32(c) : 0;
            insertpaymentlog(firstname, lastname, email, phone, c1);
            if (!string.IsNullOrEmpty(firstname) && !string.IsNullOrEmpty(lastname) )
            {
                string alerturl = "https://getultimateoffer.com/user/addalertmessage?fname=" + firstname + "&lname=" + lastname + "&phone=" + phone + "&email=" + email + "&c=" + c + "&url=";
                Get(alerturl);
            }
        }
        public string Get(string uri)
        {
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(uri);
            request.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;
            using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
            using (Stream stream = response.GetResponseStream())
            using (StreamReader reader = new StreamReader(stream))
            {
                return reader.ReadToEnd();
            }
        }
        public void insertpaymentlog(string fname,string lname,string email,string phone,int c)
        {
            SqlHelper _dt = new SqlHelper(); 
            var ip = Request.UserHostAddress;
            try
            {
                SortedList _srtlist = new SortedList();
                _srtlist.Add("@fname", fname);
                _srtlist.Add("@lname", lname);
                _srtlist.Add("@ip", ip); 
                _srtlist.Add("@email", email);
                _srtlist.Add("@phone", phone);
                _srtlist.Add("@c", c); 
                _dt.executeNonQuery("adducprotectionplanslog", "", _srtlist);
            }
            catch (Exception ex)
            {
                var a = ex.Message;
            }
            finally
            {
                _dt.Dispose();
            }
        }
        public string insertpaymentlog2(string fname, string lname, string email, string phone, int c)
        {
            string message = "";
            SqlHelper _dt = new SqlHelper();
            var ip = Request.UserHostAddress;
            try
            {
                SortedList _srtlist = new SortedList();
                _srtlist.Add("@fname", fname);
                _srtlist.Add("@lname", lname);
                _srtlist.Add("@ip", ip);
                _srtlist.Add("@email", email);
                _srtlist.Add("@phone", phone);
                _srtlist.Add("@c", c);
                _dt.executeNonQuery("adducprotectionplanslog", "", _srtlist);
            }
            catch (Exception ex)
            {
                message = ex.Message;
            }
            finally
            {
                _dt.Dispose();
            }
            return message;
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/home/Index.cshtml
@{
    ViewBag.Title = "Protection Plan Services";
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Protection Plan Services</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href="@Url.Content("~/css/style.css?v=2.3")" rel="stylesheet">
    <style>
    </style>
</head>

<!--________________body_________________-->
<body>

    <!-- Navigation -->
    <div class="container-fluid section77 d-sm-none">
        <div class="row text-center">
            <div class="col-12">
                <div style="width: 49%; float: left;">
                    <a class="navbar-brand" href="#">
                        <img src="@Url.Content("~/Image/logo.png")" width="150">
                    </a>
                </div>
                <div style="width: 49%;float: right;">
                    <h5 style="font-size: 16px!important;margin-bottom: 10px;color: #11386a;">
                        <strong>
                            Mily

                            Esteche
                        </strong>
                    </h5>
                    <h5 style="font-size: 16px!important;color: #11386a;text-decoration: none;">
                        (407) 753-4620<br>Agent
                    </h5>
                </div>
            </div>
        </div>
    </div>

    <!--- Section1 -->
    <div class="container-fluid section1" id="Home">
        <div class="dark-overlay">
            <div class="row text-center">
                <div class="col-md-6 col-lg-7">
                    <script type="text/javascript" async src="https://play.vidyard.com/embed/v4.js"></script>
                    <img style="width: 90%; margin: auto; display: block; margin-top: 20px;"
                         class="vidyard-player-embed"
                         src="https://play.vidyard.com/kmcEhqCmBg5a3mdtExVg8s.jpg"
                         data-uuid="kmcEhqCmBg5a3mdtExVg8s"
                         data-v="4"
                         data-type="inline" />
                </div>
                <div class="col-md-6 col-lg-5 pd0t">

                    <h1 class="display-4" style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif">
                        Let's Get Started with Your Free Financial Consultation
                    </h1>

                    <a href="#" onclick="notifyandredirect()" >
                        <button class="btn" style="background-color:#EFEFEF !important">
                            LEARN

                            MORE
                        </button>
                    </a>
                    <div class="dtop">
                        <h3>Mily Esteche</h3>
                        <h5 style="color: #ffd507;">
                            <i class="fa fa-phone" style="font-size:24px"></i>
                            (407) 753-

                            4620

                        </h5>
                        <h5 style="color: #ffd507;">
                            <i class="fa fa-envelope" style="font-size:24px"></i><a href="mailto:mesteche@ucprotectionplan.com"> mesteche@ucprotectionplan.com</a>
                        </h5>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!--- Section3 -->
    <div class="container-fluid section3 padding">
        <div class="row text-center padding">
            <div class="col-12">
                <h2 style="color: #3B566E;" class="inclusive">An all-inclusive financial membership...</h2>
                <p class="lead">
                    <br>

                    The all-inclusive Protection Plan was designed to support your financial opportunities by implementing positive

                    habits to create and maintain a strong financial future.
                    <br><br>
                    Our unique collection of services have been carefully selected to provide protection and opportunity

                    over the many aspects of your finances- all combined into one easy-to-use system. Your membership can

                    help to ensure you

                    and your family are safeguarding the assets that you've earned and those you have to come.<br><br>
                </p>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-3">
                <img src="@Url.Content("~/Image/Credit_restoration.png")" width="80">
                <h3 style="margin-top: 10px;color: #3B566E;">Credit Restoration</h3>
                <p class="">
                    Restore your score, create positive financial habits and maximize your financial

                    opportunities.
                </p>
            </div>
            <div class="col-sm-12 col-md-3">
                <img src="@Url.Content("~/Image/Will_Trust.png")" width="80">
                <h3 style="margin-top: 10px;color: #3B566E;">Will & Trust</h3>
                <p class="">
                    Protect your loved ones by preparing your Will & Trust documents from the comfort of your own

                    home.
                </p>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-3">
                <img src="@Url.Content("~/Image/Credit_Attorney.png")" width="80">
                <h3 style="margin-top: 10px;color: #3B566E;">Credit Attorney</h3>
                <p class="">
                    Our attorneys will evaluate your case for difficult to remove, inaccurate items on your credit

                    report.
                </p>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
                <img src="@Url.Content("~/Image/Identity_Mon.png")" width="80">
                <h3 style="margin-top: 10px;color: #3B566E;">Identity Monitoring</h3>
                <p class="">
                    Proactive monitoring that alerts you at the first sign of fraud and fully restores your

                    identity.
                </p>
            </div>
        </div>
    </div>


    <!---Section6-->
    <div class="container-fluid section6 padding">
        <div class="row padding cards">
            <div class="col-12">
                <h1 class="display-5" style="text-align: center;color: #fff">Testimonial</h1>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <p class="card-text" style="text-align: justify;">
                            It never occurred to me how much my credit

                            affected my life until something went wrong. My identity was stolen, and charges appeared in

                            my credit report.The

                            Credit Restoration program has moved me forward in my financial goals though helping me remove

                            fraudulent charges from my

                            credit report. My credit score was improved, and with the many parts of the Protection Plan, I

                            have the additional

                            resources to continue a positive financial trend for the long run.
                        </p>
                        <h4 class="card-title" style="color: #3B566E;">T. Harris</h4>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <p class="card-text" style="text-align: justify;">
                            Using The  Protection Plan helped me to take

                            control of my finances. They have the expertise and time to help me with the questions I have

                            and the things I needed

                            done. Specifically, I have been most impacted by the Credit Restoration tool. The guided me

                            through the process of

                            eliminating problematic negative items on my credit report. I am grateful to have found a

                            service to walk me through the

                            process, as I was unsure of how to go about doing it by myself.
                        </p>
                        <h4 class="card-title" style="color: #3B566E;">S. York</h4>
                    </div>
                </div>
            </div>


            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <p class="card-text" style="text-align: justify;">
                            I joined the Protection Plan for several

                            reasons, but I find myself really appreciating the Credit Builder tool. It helped us to

                            understand where we stood

                            financially, and how we could improve through easy financial activities. It might seem simple,

                            but having this option

                            available has made a real difference for me.
                        </p>
                        <h4 class="card-title" style="color: #3B566E;">M. Santos</h4>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <p class="card-text" style="text-align: justify;">
                            I’ve worked hard to earn my money and credit

                            rating, and the idea of having my good name ruined by someone stealing my identity was

                            terrifying. I signed up for the

                            Protection Plan and immediately engaged the PrivacyArmor system. It is a relief to not have to

                            worry about my information

                            being used or sold online, because the system monitors the web for me. If something were to

                            happen, they let me know, and

                            even double check on abnormal expenses when they happen. This system gives me peace of mind.
                        </p>
                        <h4 class="card-title" style="color: #3B566E;">L. James</h4>
                    </div>
                </div>
            </div>


        </div>
    </div>


    <!--- Footer -->
    <footer>
        <div class="container-fluid padding">
            <div class="row text-center">

                <div class="col-12">

                    <h5>© 2020 All Rights Reserved.</h5>
                </div>
            </div>
        </div>
    </footer>
    <script>

        function notifyandredirect() {
            var url = "https://www.ucesprotectionplan.com/default.aspx?rid=MEsteche";
            var _url = "@Url.Action("SendnotifyAsync","home")";
            $.get(_url, function (data) {
                location.href = url;
            });
        }

        function SendvisitAsync() {
            var url = "https://www.ucesprotectionplan.com/default.aspx?rid=MEsteche";
            var _url = "@Url.Action("SendvisitAsync", "home")";
            $.get(_url, function (data) {
               
            });
        }
        
    </script>

</body>
</html>